/**
 * Type for a function that returns a key from an object.
 * @category Array
 */
export type ArrayGroupByKeyFn<T> = (item: T) => string | number;

/**
 * Groups the elements of an array by a specified key generated from each element.
 *
 * This function iterates over the provided array and uses a key-generating function
 * (`keyFunc`) to determine the key for each element. The result is an object where
 * each key is associated with an array of elements that share the same key.
 *
 * @category Array
 * @param {T[]} array - The array to group.
 * @param {ArrayGroupByKeyFn<T>} keyFunc - The function to generate a key for each element.
 * @returns {Record<string | number, T[]>} An object where keys are generated by `keyFunc` and the values are arrays of elements that share the same key.
 *
 * @remarks
 * A native equivalent, `Object.groupBy`, is available in ES2024+ (Node.js ≥ 21, all modern browsers).
 * Prefer the built-in when targeting those environments:
 * ```ts
 * const grouped = Object.groupBy(arr, (item) => item.id);
 * ```
 * `arrayGroupBy` is useful for older targets or when a plain `Record<string | number, T[]>` return type
 * is preferred over the `Partial<Record<K, T[]>>` that `Object.groupBy` returns.
 *
 * @example
 * const arr = [
 *   { id: 1, name: 'Alice' },
 *   { id: 2, name: 'Bob' },
 *   { id: 1, name: 'Charlie' },
 * ];
 * const grouped = arrayGroupBy(arr, (item) => item.id);
 * console.log(grouped);
 * // Output: { 1: [{ id: 1, name: 'Alice' }, { id: 1, name: 'Charlie' }], 2: [{ id: 2, name: 'Bob' }] }
 */
export function arrayGroupBy<T>(array: T[], keyFunc: ArrayGroupByKeyFn<T>): Record<string | number, T[]> {
	const result: Record<string | number, T[]> = {};

	for (const currentValue of array) {
		const key = keyFunc(currentValue);
		result[key] ||= [];
		result[key].push(currentValue);
	}

	return result;
}
